### ISSUE TITLE
Feature request: detect if a notification already exists

### ISSUE THREAD

**Issue by ajmeese7** [Glagan/SimpleNotification#3]
It would be a really useful feature if when a new notification is opened there was an option to detect if one is already present and to decide what action to take if there is. For example, you could choose to still show the new notification (default) or to close the old one as as it closes bring in the new notification.

Currently in my project if a user clicks buttons too quickly they will have more than one notification show at once and it is not attractive with how they are styled in my app. If you do not plan on working on this I will see if I can brew up my own solution in a few months when I have time.

**Comment by Glagan** [comment]
Hi, there is a function ``disableButtons()`` than you can call inside the callbacks of your buttons.
The functions you ask for seems easy enough to do though, so I can make it.
Does the option to only have 1 notification is *global* or *per notification*, so if the option is enabled there will always be only one notification, or if a notification with the parameter is displayed it close all other notifications ?

**Comment by Glagan** [comment]
I will add the ``maxNotifications`` and ``closeAllOnDisplay`` options then.

The ``disableButtons`` function just loop trough each displayed button and add the  ``disabled`` state, so they can't be clicked.
You can call it from anywhere, any events, on button click and in general if you have a SimpleNotification object.
```javascript
// SimpleNotification.[type] return a SimpleNotification object
let n = SimpleNotification.info({
  title: "Title",
  buttons: {
    value: "Test",
    onClick: n => {
      // Inside buttons
      n.disableButtons();
    }
  }
}, {
  events: {
    onDeath: n => {
      // Inside events
      n.disableButtons();
    }
  }
});
// Basically when you have a SimpleNotification object
n.disableButtons();
```
