### ISSUE TITLE
Issue with new notification style

### ISSUE THREAD

**Issue by ajmeese7** [Glagan/SimpleNotification#9]
Before the notifications would get pretty wide to show my message in a clean manner, like this:

![old](https://user-images.githubusercontent.com/17814535/64477545-7e735a80-d162-11e9-9211-432182effae5.jpg)

But now they only get so wide then stop, leaving the messages extremely unattractive:

![new](https://user-images.githubusercontent.com/17814535/64477554-8f23d080-d162-11e9-8b21-37ea0c0e26c4.jpg)

I don't know what changed and I have been unable to pinpoint the issue myself, so I'm going to stick with using my unsupported hacky method until this is resolved. I can upload my entire old CSS if that will help you, but I'm leaving tomorrow so I won't be able to be much help fixing it.

**Comment by Glagan** [comment]
This might be related to some things I changed in the CSS file to allow animations that goes outside the notification wrappe

**Comment by Glagan** [comment]
The issue only appears on mobile, it's fine on large screens
![image](https://user-images.githubusercontent.com/8447621/64477915-30317c00-d1a1-11e9-92bd-331a351b7e8e.png)

The problem is that the wrapper doesn't have enough space since i'm using %
![image](https://user-images.githubusercontent.com/8447621/64477979-0f1d5b00-d1a2-11e9-93ec-557946f826ff.png)

**Comment by ajmeese7** [comment]
Is there a way you could fix that with media queries or something?

**Comment by Glagan** [comment]
This fix it but not really, I'm using the whole screen and set the position of the notifications with flex but if there is too much of them they stack up on the wrong direction, I realized it while I pushed.

**Comment by ajmeese7** [comment]
Just got back to the real world so I'll try out these new commits soon and get you some feedback. Thanks for trying to help!
